/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import javax.swing.*;
import java.awt.*;
//import Controleur.connexion.ConnexionControleur;
import Controleur.connexion.*;

/**
 *
 * @author aminiscloux
 */
public class FenConnexion extends javax.swing.JFrame {

    /**
     * Creates new form FenConnexion
     */
    public FenConnexion() {
        initComponents();
        complementGUI();
    }

    //Permet de customiser la FenConnexion en ligne de code
    public void complementGUI() {
        setTitle("Conseil de Section");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLab_Ecran = new javax.swing.JLabel();
        jLab_Nom = new javax.swing.JLabel();
        jLab_MDP = new javax.swing.JLabel();
        jTxT_Nom = new javax.swing.JTextField();
        jPassword_MDP = new javax.swing.JPasswordField();
        jBtn_Valider = new javax.swing.JButton();
        jBtn_Quitter = new javax.swing.JButton();
        jLab_MiniFond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_Ecran.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLab_Ecran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/ecran.png"))); // NOI18N
        jLab_Ecran.setText("Connexion au programme");
        getContentPane().add(jLab_Ecran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));
        jLab_Ecran.getAccessibleContext().setAccessibleDescription("");

        jLab_Nom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLab_Nom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/utilisateur.png"))); // NOI18N
        jLab_Nom.setText("Nom");
        getContentPane().add(jLab_Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLab_MDP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLab_MDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/key.png"))); // NOI18N
        jLab_MDP.setText("Mot de passe");
        getContentPane().add(jLab_MDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jTxT_Nom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxT_Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxT_NomActionPerformed(evt);
            }
        });
        getContentPane().add(jTxT_Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 130, -1));

        jPassword_MDP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPassword_MDP.setText("jPasswordField1");
        jPassword_MDP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPassword_MDPFocusGained(evt);
            }
        });
        getContentPane().add(jPassword_MDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 130, -1));

        jBtn_Valider.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBtn_Valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/valider.png"))); // NOI18N
        jBtn_Valider.setText("Valider");
        jBtn_Valider.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jBtn_Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ValiderActionPerformed(evt);
            }
        });
        jBtn_Valider.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtn_ValiderKeyPressed(evt);
            }
        });
        getContentPane().add(jBtn_Valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jBtn_Quitter.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBtn_Quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection/quitter.png"))); // NOI18N
        jBtn_Quitter.setText("Quitter");
        jBtn_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_QuitterActionPerformed(evt);
            }
        });
        jBtn_Quitter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtn_QuitterKeyPressed(evt);
            }
        });
        getContentPane().add(jBtn_Quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLab_MiniFond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fond.png"))); // NOI18N
        getContentPane().add(jLab_MiniFond, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 410, 300));

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        //Bouton Quitter valide la sélection pour fermer l'application
    private void jBtn_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_QuitterActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBtn_QuitterActionPerformed

    //Bouton Entrée sur Quitter valide la sélection pour fermer l'application
    private void jBtn_QuitterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtn_QuitterKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            System.exit(0);
        }
    }//GEN-LAST:event_jBtn_QuitterKeyPressed

    //Bouton Entrée sur Valider valide la sélection pour accéder à la FenMenuPrincipal
    private void jBtn_ValiderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtn_ValiderKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            FenMenuPrincipal laFenetre = new FenMenuPrincipal() ;
            laFenetre.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jBtn_ValiderKeyPressed
    
//Bouton Valider valide la sélection pour accéder à la FenMenuPrincipal
    private void jBtn_ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ValiderActionPerformed
        // TODO add your handling code here:
       /* FenMenuPrincipal laFenetre = new FenMenuPrincipal();
        laFenetre.setVisible(true);
        dispose();*/
        String login = jTxT_Nom.getText();
        String mdp = new String(jPassword_MDP.getPassword());
        AuthentificationControleur.traitementLogIn(login,mdp,this);
    }//GEN-LAST:event_jBtn_ValiderActionPerformed

    private void jTxT_NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxT_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxT_NomActionPerformed

    private void jPassword_MDPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPassword_MDPFocusGained
        // TODO add your handling code here:
        jPassword_MDP.setText("");
    }//GEN-LAST:event_jPassword_MDPFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenConnexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Quitter;
    private javax.swing.JButton jBtn_Valider;
    private javax.swing.JLabel jLab_Ecran;
    private javax.swing.JLabel jLab_MDP;
    private javax.swing.JLabel jLab_MiniFond;
    private javax.swing.JLabel jLab_Nom;
    private javax.swing.JPasswordField jPassword_MDP;
    private javax.swing.JTextField jTxT_Nom;
    // End of variables declaration//GEN-END:variables
}
