/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

/**
 *
 * @author aminiscloux
 */
public class FenMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FenMenuPrincipal
     */
    public FenMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane_Principal = new javax.swing.JDesktopPane();
        jMenuBar_Principal = new javax.swing.JMenuBar();
        jMenu_Admin = new javax.swing.JMenu();
        jMenu_Utilisateurs = new javax.swing.JMenu();
        jMenuItem_Formateurs = new javax.swing.JMenuItem();
        jMenuItem_Etudiants = new javax.swing.JMenuItem();
        jMenuItem_Filières = new javax.swing.JMenuItem();
        jMenu_RF = new javax.swing.JMenu();
        jMenu_ListeApprentis = new javax.swing.JMenu();
        jMenu_Autre = new javax.swing.JMenu();
        jMenuItem_Quitter = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSEIL DE SECTION");

        javax.swing.GroupLayout jDesktopPane_PrincipalLayout = new javax.swing.GroupLayout(jDesktopPane_Principal);
        jDesktopPane_Principal.setLayout(jDesktopPane_PrincipalLayout);
        jDesktopPane_PrincipalLayout.setHorizontalGroup(
            jDesktopPane_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        jDesktopPane_PrincipalLayout.setVerticalGroup(
            jDesktopPane_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );

        jMenu_Admin.setText("Administrateur");

        jMenu_Utilisateurs.setText("Gestion des utilisateurs");

        jMenuItem_Formateurs.setText("Gestion des formateurs");
        jMenuItem_Formateurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_FormateursActionPerformed(evt);
            }
        });
        jMenu_Utilisateurs.add(jMenuItem_Formateurs);

        jMenuItem_Etudiants.setText("Gestion des étudiants");
        jMenu_Utilisateurs.add(jMenuItem_Etudiants);

        jMenu_Admin.add(jMenu_Utilisateurs);

        jMenuItem_Filières.setText("Gestion des filières");
        jMenuItem_Filières.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_FilièresActionPerformed(evt);
            }
        });
        jMenu_Admin.add(jMenuItem_Filières);

        jMenuBar_Principal.add(jMenu_Admin);

        jMenu_RF.setText("Responsable de filière");

        jMenu_ListeApprentis.setText("Liste des apprentis");
        jMenu_RF.add(jMenu_ListeApprentis);

        jMenuBar_Principal.add(jMenu_RF);

        jMenu_Autre.setText("Autre");
        jMenu_Autre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_AutreActionPerformed(evt);
            }
        });

        jMenuItem_Quitter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Quitter.setText("Quitter");
        jMenuItem_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_QuitterActionPerformed(evt);
            }
        });
        jMenu_Autre.add(jMenuItem_Quitter);

        jMenuBar_Principal.add(jMenu_Autre);

        setJMenuBar(jMenuBar_Principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1016, 839));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_QuitterActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_QuitterActionPerformed

    private void jMenu_AutreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_AutreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu_AutreActionPerformed

    private void jMenuItem_FormateursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_FormateursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_FormateursActionPerformed

    //Ajouter la fenêtre interne au DesktopPane
    private void jMenuItem_FilièresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_FilièresActionPerformed
        // TODO add your handling code here:
        JIFFilière laFenetreInterne = new JIFFilière();
        jDesktopPane_Principal.add(laFenetreInterne);
        laFenetreInterne.setVisible(true);
    }//GEN-LAST:event_jMenuItem_FilièresActionPerformed


    //Définition de l'ensemble des variables
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane_Principal;
    private javax.swing.JMenuBar jMenuBar_Principal;
    private javax.swing.JMenuItem jMenuItem_Etudiants;
    private javax.swing.JMenuItem jMenuItem_Filières;
    private javax.swing.JMenuItem jMenuItem_Formateurs;
    private javax.swing.JMenuItem jMenuItem_Quitter;
    private javax.swing.JMenu jMenu_Admin;
    private javax.swing.JMenu jMenu_Autre;
    private javax.swing.JMenu jMenu_ListeApprentis;
    private javax.swing.JMenu jMenu_RF;
    private javax.swing.JMenu jMenu_Utilisateurs;
    // End of variables declaration//GEN-END:variables
}
