/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Controleur.connexion.AdministrateurControleur;
import Modele.AppartenirPromotion;
import Modele.ChoisirFiliere;
import Modele.Eleve;
import Modele.Filiere;
import Modele.Promotion;
import java.awt.Font;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aminiscloux
 */
public class JIFEtudiant extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public JIFEtudiant() {
        initComponents();
        this.sizeFont();
        this.tableau();
        this.comboFiliere();
        this.comboPromo();

    }

    public void sizeFont() {
        jBtnValider.setFont(new Font("Arial", Font.PLAIN, 20));
        jBtnAjouter.setFont(new Font("Arial", Font.PLAIN, 20));
        jFiltreFiliere.setFont(new Font("Arial", Font.PLAIN, 20));
        jFiltrePromotion.setFont(new Font("Arial", Font.PLAIN, 20));
        jLabelNom.setFont(new Font("Arial", Font.PLAIN, 20));
        jLabelFiltre.setFont(new Font("Arial", Font.PLAIN, 20));
        jTableEtudiant.setFont(new Font("Arial", Font.PLAIN, 20));
        jTextNom.setFont(new Font("Arial", Font.PLAIN, 20));
    }

    public void tableau() {
        DefaultTableModel model = (DefaultTableModel) jTableEtudiant.getModel();
        model.getDataVector().clear();

        ArrayList<Eleve> liste = AdministrateurControleur.ListeEtudiant();
        for (int i = 0; i < liste.size(); i++) {
            //Recupere la liste des filieres d'un étudiant
            ArrayList<ChoisirFiliere> tabFiliere = liste.get(i).getFiliere();
            String listFiliere = "";
            for (ChoisirFiliere s : tabFiliere) {
                listFiliere += s.getFiliere().getLibelle() + System.getProperty("line.separator");
            }
            //Multiligne
            JLabel test = new JLabel();
            String listFiliereBr = listFiliere.replace("\n", "<br>");
            test.setText("<html>" + listFiliereBr + "</html>");
            //Recupere la liste des promotions de l'élève
            ArrayList<AppartenirPromotion> tabPromo = liste.get(i).getPromo();
            String listPromo = "";
            for (AppartenirPromotion t : tabPromo) {
                listPromo += t.getPromotion().getAnnee() + "; ";
            }
            //Ajoute les lignes au tableau élève
            model.addRow(new Object[]{
                liste.get(i).getUser().getId(),
                liste.get(i).getUser().getNom(),
                liste.get(i).getUser().getPrenom(),
                liste.get(i).getFiliere(),
                test.getText(), // multiligne
                //listFiliere.substring(0, listFiliere.length() - 2), //moins le '; ' final
                liste.get(i).getPromo(),
                listPromo.substring(0, listPromo.length() - 2),});
            //Adpater la taille des lignes
            jTableEtudiant.setRowHeight(calculHauteur(test.getText()));
        }
    }

    private int calculHauteur(String s) {
        //nombre de lignes dans la chaine
        String[] lignes = s.split("<br>");
        int nbLignes = 0;
        for (String ligne : lignes) {
            nbLignes += 1;
        }
        //taille d'une ligne dans le tableau
        int tailleLigne = 0;
        for (int i = 0; i < nbLignes; i++) {
            tailleLigne += 26;
        }
        return tailleLigne;
    }

    public void comboFiliere() {
        jFiliere.removeAllItems();
        jFiltreFiliere.removeAllItems();
        jFiliere.addItem("");
        jFiltreFiliere.addItem("");
        ArrayList<Filiere> list = AdministrateurControleur.ListeFiliere();
        for (Filiere x : list) {
            jFiltreFiliere.addItem(x.getLibelle());
            jFiliere.addItem(x.getLibelle());
        }
    }

    public void comboPromo() {
        jPromotion.removeAllItems();
        jFiltrePromotion.removeAllItems();
        jPromotion.addItem("");
        jFiltrePromotion.addItem("");
        ArrayList<Promotion> list = AdministrateurControleur.ListePromotion();
        for (Promotion x : list) {
            jPromotion.addItem(Integer.toString(x.getAnnee()));
            jFiltrePromotion.addItem(Integer.toString(x.getAnnee()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFiltre = new javax.swing.JPanel();
        jLabelNom = new javax.swing.JLabel();
        jTextNom = new javax.swing.JTextField();
        jLabelFiltre = new javax.swing.JLabel();
        jBtnValider = new javax.swing.JButton();
        jFiltreFiliere = new javax.swing.JComboBox<>();
        jFiltrePromotion = new javax.swing.JComboBox<>();
        jBtnAjouter = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jIdEtu = new javax.swing.JTextField();
        jNom = new javax.swing.JTextField();
        jPrenom = new javax.swing.JTextField();
        jFiliere = new javax.swing.JComboBox<>();
        jPromotion = new javax.swing.JComboBox<>();
        jAge = new javax.swing.JTextField();
        jNumRue = new javax.swing.JTextField();
        jRue = new javax.swing.JTextField();
        jCP = new javax.swing.JTextField();
        jVille = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableFiliere = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePromotion = new javax.swing.JTable();
        jBtnSupprimer = new javax.swing.JButton();
        jBtnModifier = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEtudiant = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des filières");
        setPreferredSize(new java.awt.Dimension(2160, 1440));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFiltre.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNom.setText("Nom");

        jLabelFiltre.setText("Filtre :");

        jBtnValider.setText("Valider");

        jFiltreFiliere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jFiltrePromotion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBtnAjouter.setText("Ajouter un étudiant");

        javax.swing.GroupLayout jPanelFiltreLayout = new javax.swing.GroupLayout(jPanelFiltre);
        jPanelFiltre.setLayout(jPanelFiltreLayout);
        jPanelFiltreLayout.setHorizontalGroup(
            jPanelFiltreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFiltreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelFiltre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelFiltreLayout.createSequentialGroup()
                        .addComponent(jLabelNom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jFiltreFiliere, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFiltrePromotion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(357, 357, 357)
                .addGroup(jPanelFiltreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAjouter)
                    .addComponent(jBtnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelFiltreLayout.setVerticalGroup(
            jPanelFiltreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltreLayout.createSequentialGroup()
                .addGroup(jPanelFiltreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFiltre)
                    .addComponent(jBtnAjouter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFiltreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFiltreFiliere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFiltreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFiltrePromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnValider))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelFiltre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 240));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jIdEtu.setEditable(false);
        jIdEtu.setText("Id");
        jIdEtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIdEtuActionPerformed(evt);
            }
        });

        jNom.setText("Nom");
        jNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomActionPerformed(evt);
            }
        });

        jPrenom.setText("Prenom");

        jFiliere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPromotion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jAge.setText("Age");

        jNumRue.setText("N°");

        jRue.setText("Rue");

        jCP.setText("jCP");

        jVille.setText("Ville");

        jTableFiliere.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Filiere"
            }
        ));
        jScrollPane4.setViewportView(jTableFiliere);

        jTablePromotion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Promotion"
            }
        ));
        jScrollPane1.setViewportView(jTablePromotion);

        jBtnSupprimer.setText("Supprimer");
        jBtnSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSupprimerMouseClicked(evt);
            }
        });

        jBtnModifier.setText("Modifier");
        jBtnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jIdEtu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jCP)
                        .addComponent(jNumRue, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jAge, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jNom, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jFiliere, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnModifier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)))
                .addGap(174, 174, 174)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jPrenom)
                    .addComponent(jVille)
                    .addComponent(jRue)
                    .addComponent(jPromotion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jIdEtu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFiliere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNumRue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSupprimer)
                    .addComponent(jBtnModifier))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 880, 870));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTableEtudiant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nom", "Prénom", "idFiliere", "Filière", "idPromotion", "Promotion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEtudiant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEtudiantMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableEtudiant);
        if (jTableEtudiant.getColumnModel().getColumnCount() > 0) {
            jTableEtudiant.getColumnModel().getColumn(0).setMinWidth(0);
            jTableEtudiant.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTableEtudiant.getColumnModel().getColumn(0).setMaxWidth(0);
            jTableEtudiant.getColumnModel().getColumn(3).setMinWidth(0);
            jTableEtudiant.getColumnModel().getColumn(3).setPreferredWidth(0);
            jTableEtudiant.getColumnModel().getColumn(3).setMaxWidth(0);
            jTableEtudiant.getColumnModel().getColumn(5).setMinWidth(0);
            jTableEtudiant.getColumnModel().getColumn(5).setPreferredWidth(0);
            jTableEtudiant.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 830, 610));

        setBounds(0, 0, 1774, 956);
    }// </editor-fold>//GEN-END:initComponents

    private void jNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomActionPerformed

    private void jIdEtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIdEtuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIdEtuActionPerformed

    private void jTableEtudiantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEtudiantMouseClicked
        // TODO add your handling code here:
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        int iduser = Integer.parseInt(jTableEtudiant.getValueAt(row, 0).toString());

        Eleve selected = AdministrateurControleur.SelectedEtudiant(iduser);
        jIdEtu.setText(Integer.toString(selected.getUser().getId()));
        jNom.setText(selected.getUser().getNom());
        jPrenom.setText(selected.getUser().getPrenom());
        jAge.setText(Integer.toString(selected.getAge()));
        jNumRue.setText(Integer.toString(selected.getNumRue()));
        jRue.setText(selected.getLibelleRue());
        jCP.setText(Integer.toString(selected.getCodePostal()));
        jVille.setText(selected.getVille());
        DefaultTableModel model = (DefaultTableModel) jTableFiliere.getModel();
        model.getDataVector().clear();
        ArrayList<ChoisirFiliere> liste = selected.getFiliere();
        //Recupere la liste des filieres d'un étudiant
        for (int i = 0; i < liste.size(); i++) {
            model.addRow(new Object[]{
                    liste.get(i).getFiliere().getLibelle(),
            });
        }
        DefaultTableModel model1 = (DefaultTableModel) jTablePromotion.getModel();
        model1.getDataVector().clear();
        ArrayList<AppartenirPromotion> liste1 = selected.getPromo();
        //Recupere la liste des filieres d'un étudiant
        for (int i = 0; i < liste1.size(); i++) {
            model1.addRow(new Object[]{
                    liste1.get(i).getPromotion().getAnnee()
            });
        }


    }//GEN-LAST:event_jTableEtudiantMouseClicked

    private void jBtnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnModifierActionPerformed

    private void jBtnSupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSupprimerMouseClicked
        // TODO add your handling code here:
        int idUser;
        if (jIdEtu.getText().equals("")){
            idUser=-1;
        } else {
            idUser=Integer.parseInt(jIdEtu.getText());
        }
        if (idUser != -1){
            AdministrateurControleur.SupprimerEleve(idUser, this);
        } else {
            JOptionPane.showMessageDialog(null,
                    "Erreur suppression, sélectionner un élève.",
                    "Résultat", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnSupprimerMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAge;
    private javax.swing.JButton jBtnAjouter;
    private javax.swing.JButton jBtnModifier;
    private javax.swing.JButton jBtnSupprimer;
    private javax.swing.JButton jBtnValider;
    private javax.swing.JTextField jCP;
    private javax.swing.JComboBox<String> jFiliere;
    private javax.swing.JComboBox<String> jFiltreFiliere;
    private javax.swing.JComboBox<String> jFiltrePromotion;
    private javax.swing.JTextField jIdEtu;
    private javax.swing.JLabel jLabelFiltre;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JTextField jNom;
    private javax.swing.JTextField jNumRue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelFiltre;
    private javax.swing.JTextField jPrenom;
    private javax.swing.JComboBox<String> jPromotion;
    private javax.swing.JTextField jRue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableEtudiant;
    private javax.swing.JTable jTableFiliere;
    private javax.swing.JTable jTablePromotion;
    private javax.swing.JTextField jTextNom;
    private javax.swing.JTextField jVille;
    // End of variables declaration//GEN-END:variables
}
