/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

/**
 *
 * @author aminiscloux
 */
public class JIFFormateur extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFFormateur
     */
    public JIFFormateur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtNomFiltre = new javax.swing.JTextField();
        jLabNomFiltre = new javax.swing.JLabel();
        jTxtPrenomFiltre = new javax.swing.JTextField();
        jLabPrenomFiltre = new javax.swing.JLabel();
        jBtnFiltrer = new javax.swing.JButton();
        jLabNomNouveau = new javax.swing.JLabel();
        jTxtNomNouveau = new javax.swing.JTextField();
        jLabPrenomNouveau = new javax.swing.JLabel();
        jTxtPrenomNouveau = new javax.swing.JTextField();
        jBtnAjouter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des formateurs");
        setPreferredSize(new java.awt.Dimension(2160, 1440));

        jTxtNomFiltre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomFiltreActionPerformed(evt);
            }
        });

        jLabNomFiltre.setText("NOM :");

        jLabPrenomFiltre.setText("Prénom :");

        jBtnFiltrer.setText("Filtrer");

        jLabNomNouveau.setText("NOM :");

        jTxtNomNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomNouveauActionPerformed(evt);
            }
        });

        jLabPrenomNouveau.setText("Prénom :");

        jBtnAjouter.setText("Ajouter un formateur");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IdFormateur", "NomFormateur", "PrenomFormateur"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabNomFiltre)
                            .addComponent(jLabPrenomFiltre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtNomFiltre)
                            .addComponent(jTxtPrenomFiltre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnFiltrer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnAjouter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabNomNouveau)
                                    .addComponent(jLabPrenomNouveau))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtPrenomNouveau)
                                    .addComponent(jTxtNomNouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(450, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNomFiltre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabNomFiltre)
                    .addComponent(jLabNomNouveau)
                    .addComponent(jTxtNomNouveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPrenomFiltre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabPrenomFiltre)
                    .addComponent(jLabPrenomNouveau)
                    .addComponent(jTxtPrenomNouveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnFiltrer)
                    .addComponent(jBtnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        setBounds(0, 0, 929, 633);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNomFiltreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomFiltreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomFiltreActionPerformed

    private void jTxtNomNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomNouveauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomNouveauActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAjouter;
    private javax.swing.JButton jBtnFiltrer;
    private javax.swing.JLabel jLabNomFiltre;
    private javax.swing.JLabel jLabNomNouveau;
    private javax.swing.JLabel jLabPrenomFiltre;
    private javax.swing.JLabel jLabPrenomNouveau;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtNomFiltre;
    private javax.swing.JTextField jTxtNomNouveau;
    private javax.swing.JTextField jTxtPrenomFiltre;
    private javax.swing.JTextField jTxtPrenomNouveau;
    // End of variables declaration//GEN-END:variables
}
