/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

/**
 *
 * @author aminiscloux
 */
public class JIFFilière extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public JIFFilière() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Carte = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des filières");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Carte.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_Carte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gestion/carte.png"))); // NOI18N
        getContentPane().add(jLabel_Carte, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 162, -1, -1));

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField1.setText("Pitié, faites un don pour le CFAI");
        jTextField1.setEditable(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 115, -1, -1));

        setBounds(0, 0, 410, 308);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Carte;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
